<?php

declare(strict_types=1);

namespace VasilDakov\SpeedyTest\Shipment;

use PHPUnit\Framework\TestCase;
use VasilDakov\Speedy\Shipment\ShipmentContent;
use VasilDakov\Speedy\Shipment\ShipmentParcel;

/**
 * Class ShipmentContentTest
 *
 * @author Valentin Valkanov <valentinvalkanof@gmail.com>
 * @copyright
 * @version
 */
class ShipmentContentTest extends TestCase
{
    protected function setUp(): void
    {
        $this->parcelsCount = 1;
        $this->totalWeigth = 3.5;
        $this->contents = "Some content";
        $this->package = "Package";
        $this->parcel = $this->createMock(ShipmentParcel::class);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     * * &group CreateShipmentRequest
     */
    public function testItCanBeCreated() :void
    {
        $object = new ShipmentContent($this->parcelsCount, $this->totalWeigth, $this->contents, $this->package, $this->parcel);

        $this->assertInstanceOf(ShipmentContent::class, $object);
    }

}