<?php

declare(strict_types=1);


namespace VasilDakov\SpeedyTest\ValueObject;

use Example\Address;
use Example\Email;
use PHPUnit\Framework\TestCase;
use VasilDakov\Speedy\ValueObject\CountryCode;

/**
 * Class CountryCodeTest
 *
 * @author Vasil Dakov <vasildakov@gmail.com>
 * @copyright 2009-2022 Neutrino.bg
 * @version 1.0
 */
class CountryCodeTest extends TestCase
{
    protected $phone;
    protected $email;

    protected function setUp(): void
    {
        $this->email = $this->createMock(Email::class);
        $this->phone = $this->createMock(Phone::class);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @group countryCode
     */
    public function testItCanBeCreatedWithBulgariaCode()
    {
        $address = new Address($this->email, $this->phone);

        $object = new CountryCode(CountryCode::BGR);
        $this->assertInstanceOf(CountryCode::class, $object);
    }

    /**
     * @group countryCode
     */
    public function testItCanBeCreatedWithRomaniaCode()
    {
        $this->assertInstanceOf(CountryCode::class, new CountryCode(CountryCode::ROU));
    }
}
