<?php

declare(strict_types=1);

namespace VasilDakov\SpeedyTests\Service\Shipment;

use PHPUnit\Framework\TestCase;
use VasilDakov\Speedy\Service\Shipment\ShipmentAdditionalServices;
use VasilDakov\Speedy\Service\Shipment\ShipmentService;
use VasilDakov\Speedy\Speedy;

/**
 * Class ShipmentServiceTest.
 *
 * @author Valentin Valkanov <valentinvalkanof@gmail.com>
 * @copyright
 *
 * @version
 */
class ShipmentServiceTest extends TestCase
{
    protected \DateTime $pickupDate;

    protected bool $autoAdjustPickupDate = false;

    protected int $serviceId;

    protected ShipmentAdditionalServices $additionalServices;

    protected int $deferredDays;

    protected bool $saturdayDelivery = false;

    protected function setUp(): void
    {
        $this->pickupDate = $this->createMock(\DateTime::class);
        $this->autoAdjustPickupDate = false;
        $this->serviceId = 5;
        $this->additionalServices = $this->createMock(ShipmentAdditionalServices::class);
        $this->deferredDays = 6;
        $this->saturdayDelivery = false;

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testItCanExportToArrayWithMandatoryProperty(): void
    {
        $object = new ShipmentService($this->serviceId);

        $array = $object->toArray();

        $this->assertArrayHasKey(Speedy::SERVICE_ID, $array);
    }

    public function testItCanExportToArrayWithOptionalProperty(): void
    {
        $object = new ShipmentService($this->serviceId);

        $object->setAutoAdjustPickupDate($this->autoAdjustPickupDate);
        $object->setAdditionalServices($this->additionalServices);
        $object->setDeferredDays($this->deferredDays);
        $object->setSaturdayDelivery($this->saturdayDelivery);
        $object->setPickupDate($this->pickupDate);

        $array = $object->toArray();

        // $this->assertArrayHasKey(Speedy::AUTO_ADJUST_PICKUP_DATE, $array);
        $this->assertArrayHasKey(Speedy::ADDITIONAL_SERVICES, $array);
        $this->assertArrayHasKey(Speedy::DEFERRED_DAYS, $array);
        // $this->assertArrayHasKey(Speedy::SATURDAY_DELIVERY, $array);
        $this->assertArrayHasKey(Speedy::PICKUP_DATE, $array);
    }
}
